### ISSUE TITLE
No popup for SciFireaders

### ISSUE THREAD

**Issue by slps9061008** [pycroscopy/SciFiReaders#75]
Hi

I used the following code, but it could not popup interactive window in spyder, do you know how it might help?

%pylab notebook
%gui qt
import os
import sys
from sidpy.io.interface_utils import openfile_dialog_QT
sys.path.append('../')
from SciFiReaders import IgorIBWReader
import SciFiReaders
print('SciFiReaders version: ', SciFiReaders.version)
import sidpy
print('sidpy version: ', sidpy.version)

**Comment by gduscher** [comment]
Hi back,
sorry for the long delay in answering this. 
You need to open the file dialog with a line like:
> filename = openfile_dialog()
and then read that file with:
> reader = IgorIBWReader(file_name)
> dataset = reader.read()

See the notebooks for help.
You can load notebooks in spyder or just copy and past the first FEW code cells into your program.

Hope this helps,
Gerd
