### ISSUE TITLE
Unable to read *ibw files with IgorIBWReader

### ISSUE THREAD

**Issue by tenoriomaria** [pycroscopy/SciFiReaders#84]
Hi there,

I am trying to read my *ibw files with SciFiReaders library.
This is my code:

import SciFiReaders as sr
reader = sr.IgorIBWReader('/path_to_file/file.ibw')
reader.read()

And this is the output:

----> 4 reader.read()

~/opt/anaconda3/envs/pycroscopy/lib/python3.7/site-packages/SciFiReaders/readers/microscopy/spm/afm/igor_ibw.py in read(self, verbose, parm_encoding)
     45 
     46         # Load the ibw file first
---> 47         ibw_obj = bw.load(file_path)
     48         ibw_wave = ibw_obj.get('wave')
     49         parm_dict = self._read_parms(ibw_wave, parm_encoding)

AttributeError: 'NoneType' object has no attribute 'load'
[file.ibw.zip](https://github.com/pycroscopy/SciFiReaders/files/8908740/file.ibw.zip)

Thanks a lot in advance!

**Comment by ramav87** [comment]
Closing.
