### ISSUE TITLE
Changing Igor to Igor2

### ISSUE THREAD

**Issue by rajgiriUW** [pycroscopy/SciFiReaders#96]
I recently found out (when trying to do the same thing) that [Igor2 ](https://github.com/AFM-analysis/igor2
) has supplanted the very old and un-updated Igor, which throws errors with modern version of numpy. 

I will fix this as it's trivial, but wanted to write this issue in part if people Google about Igor2.

**Comment by ramav87** [comment]
Oh wow, ok. That is good to know!

**Comment by nsulmol** [comment]
I also had this issue, so I made a pull request. Please see the associated fix (#97, though it should be linked here).
